Addons sender
mgutierrezc/sms_api_sender pull request #3
Opened 2021-12-18 22:13 UTC by Sweetdreamstome

2021-12-18 22:26 UTC, mgutierrezc requested changes

2021-12-18 22:26 UTC, mgutierrezc commented on sms_tools/sms_sending_tools.py
> +        self.additional_param=additional_param
Borrar estos params

2021-12-18 22:26 UTC, mgutierrezc commented on sms_tools/sms_sending_tools.py
> +        if name and additional_param != "":
if len(var1)>0:
    var1= " " + var1
if len(...)

return base_text.format(var1, ...)

2021-12-18 23:49 UTC, Sweetdreamstome commented
@mgutierrezc ya agregué lo que pediste en el issue, en caso que solo exista una columna en el csv, se agregaran dos columnas con los nombres "nombre" y "parametro" con espacios vacios. Si hay más de una columna en el csv, no se hará lo anterior.

2021-12-18 23:56 UTC, mgutierrezc requested changes

2021-12-18 23:56 UTC, mgutierrezc commented on sms_tools/sms_sending_tools.py
> +                list.append("")
Usa [""]*len(data_frame)

2021-12-18 23:56 UTC, mgutierrezc commented on sms_tools/sms_sending_tools.py
> +                list.append("")
@Sweetdreamstome

2021-12-19 00:09 UTC, Sweetdreamstome commented on sms_tools/sms_sending_tools.py
> +                list.append("")
@mgutierrezc ya lo agrege!

2021-12-19 00:15 UTC, mgutierrezc approved these changes

2021-12-19 00:15 UTC, merged